module: JazzyKit
author: PSPDFKit
author_url: http://pspdfkit.com/
objc: true
clean: true
framework_root: .
umbrella_header: MiscJazzyObjCFeatures/MiscJazzyObjCFeatures.h
sdk: iphonesimulator
custom_categories:
- name: Ying
  children:
  - ObjCTopLevelClass