module: MiscJazzyFeatures
author: Realm
title: Examples of Jazzy Swift documentation
author_url: https://github.com/realm/jazzy
github_url: https://github.com/realm/jazzy
min_acl: private
hide_documentation_coverage: true
documentation: Extra/*.md
abstract: Sections/*.md
theme: jony
exclude: "MiscJazzyFeatures/*gnor*"
use_safe_filenames: true

custom_categories:
  - name: Guides
    children:
    - Example 1
    - Example 2
    - Example ℵ
  - name: "Yin: A Category"
    children:
    - PublicTopLevelClass
    - PrivateTopLevelClass
    - documentedGlobal
  - name: Yang
    children:
    - TopLevelObjCSubclass
    - UndocumentedEnum
