module: MiscJazzyFeatures
author: Realm
author_url: https://github.com/realm/jazzy
github_url: https://github.com/realm/jazzy
min_acl: private
hide_documentation_coverage: true
documentation: Extra/*.md
abstract: Sections/*.md
xcodebuild_arguments: 
  - '-dry-run'
theme: fullwidth

custom_categories:
  - name: Guides
    children:
    - Example 1
    - Example 2
  - name: Yin
    children:
    - PublicTopLevelClass
    - PrivateTopLevelClass
    - documentedGlobal
  - name: Yang
    children:
    - TopLevelObjCSubclass
    - UndocumentedEnum
